version: "3.8" 

services:
  # Extractor service
  hf_extractor:
    build: 
      context: ./Extractors/HF_Extractor
      dockerfile: Dockerfile  # Path to extractor Dockerfile
    # Define volumes to mount extractor scripts or dependencies
    volumes:
      - ./Extractors/HF_Extractor:/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    dns:
      - 1.1.1.1
    # networks:
    #   - my-macvlan-net

  # Transformer service
  # transformer:
  #   build: ./transformer  # Path to your transformer Dockerfile
  #   # Define volumes to mount transformation logic
  #   volumes:
  #     - ./transformer:/app/transformer  # Example volume mapping for transformation code
  #   depends_on:
  #     - extractor  # Wait for extractor to finish before starting transformer

  # Loader service
  # loader:
  #   build: ./loader  # Path to your loader Dockerfile
  #   # Optional: Define volumes for output data or database connection details
  #   volumes:
  #     - ./loader:/app/loader  # Example volume mapping for loader code
  #   depends_on:
  #     - transformer  # Wait for transformer to finish before starting loader

# networks:
#   my-macvlan-net:
#     external: true
#     name: my-macvlan-net
#   host:
#     external: true

