version: 2.1

  
# executors:
#   docker:
#     image: ubuntu:20.04

jobs:
  build:
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Go to the production folder
          command: cd Backend/
      - run:
          name: Check docker-compose version 
          command: docker-compose --version
      - run:
          name: Build the container architecture
          command: docker-compose --profile no_gpu build
      # - docker-compose up -d
      # - docker-compose logs -f


workflows:
  build-and-test:
    jobs:
      - build

      