version: 2.1

  
# executors:
#   docker:
#     image: ubuntu:20.04

jobs:
  build_and_test:
    machine: # executor type
      image: ubuntu-2204:2024.01.2
    # working_directory: /Backend
    steps:
      - run:
          name: Install last version of Docker Compose
          command: |
            sudo apt-get remove docker-compose
            VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')
            DESTINATION=/usr/local/bin/docker-compose
            sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION
            sudo chmod 755 $DESTINATION
      - run:
          name: Check Docker version
          command: docker --version
      - checkout
      - run:
          name: 
          command: ls
      - run:
          name: Check docker-compose version 
          command: docker-compose --version
          working_directory: ./tests
      - run:
          name: Add permissions to execution files 
          command: |
            chmod +x ./validate_tests.sh
            chmod +x ./wait-for-it.sh
          working_directory: ./tests
      - run:
          name: Build the container architecture
          command: docker-compose --profile test build
          working_directory: ./tests
      - run:
          name: Run the project tests.
          working_directory: ./tests
          command: sh validate_tests.sh
      # - docker-compose logs -f


workflows:
  build-and-test:
    jobs:
      - build_and_test

      