version: 2.1

  
# executors:
#   docker:
#     image: ubuntu:20.04

jobs:
  build:
    machine: # executor type
      image: ubuntu-2004:202010-01
    # working_directory: /Backend
    steps:
      - run:
          name: 
          command: ls
      - run:
          name: Check docker-compose version 
          command: docker-compose --version
          working_directory: ./Backend
      - run:
          name: Build the container architecture
          command: docker-compose --profile no_gpu build
          working_directory: /Backend
      # - docker-compose up -d
      # - docker-compose logs -f


workflows:
  build-and-test:
    jobs:
      - build

      