version: 2.1

executor:
  name: docker

jobs:
  build:
    steps:
      - checkout
      - service: docker # Service pre-installs Docker and docker-compose
      - working_directory: ./Backend
      - docker-compose pull
      - docker-compose up -d
      - docker-compose logs -f

workflows:
  build-and-test:
    jobs:
      - build

      