version: 2.1

  
# executors:
#   docker:
#     image: ubuntu:20.04

jobs:
  build:
    machine: # executor type
      image: ubuntu-2004:202010-01
    # working_directory: /Backend
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get remove docker-compose
            VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')
            DESTINATION=/usr/local/bin/docker-compose
            sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION
            sudo chmod 755 $DESTINATION
      - run:
          name: 
          command: ls
      - run:
          name: Check docker-compose version 
          command: docker-compose --version
          working_directory: ./Backend
      - run:
          name: Build the container architecture
          command: docker-compose --profile no_gpu build
          working_directory: ./Backend
      # - docker-compose up -d
      # - docker-compose logs -f


workflows:
  build-and-test:
    jobs:
      - build

      