version: 2.1

# machine:
#   image: ubuntu-2004

jobs:
  build:
    executor: docker
    working_directory: ./Backend
    steps:
      - checkout
      - docker-compose pull
      - docker-compose up -d
      - docker-compose logs -f

workflows:
  build-and-test:
    jobs:
      - build

      