FROM python:3.11-slim AS no_gpu_base

WORKDIR /app

RUN pip install --upgrade pip && pip install packaging

COPY deployment/requirements/ /app/requirements/

RUN pip install --no-cache-dir -r /app/requirements/ai4life_no_gpu_requirements.txt

COPY code/extractors /app/extractors
RUN pip3 install --no-deps -e /app/extractors

COPY code/transform /app/transform
RUN pip3 install --no-deps -e /app/transform

COPY code/load /app/load
RUN pip3 install --no-deps -e /app/load

FROM no_gpu_base AS no_gpu_ai4life
RUN echo "Building AI4Life ETL image without GPU..."
