FROM python:3.11

RUN pip3 install torch -f https://download.pytorch.org/whl/cu113

# Create working directory
WORKDIR /app

# Copy the package files
COPY code/extractors /app/extractors
RUN pip3 install -e /app/extractors

COPY code/transform /app/transform
RUN pip3 install -e /app/transform

COPY code/load /app/load
RUN pip3 install -e /app/load

