FROM python:3.11

RUN pip3 install torch -f https://download.pytorch.org/whl/cu113

ENV DOCKER_VERSION=18.09.4
RUN curl -sfL -o docker.tgz "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" && \
tar -xzf docker.tgz docker/docker --strip=1 --directory /usr/local/bin && \
rm docker.tgz

COPY ./tests/config/requirements.txt .
RUN pip3 install -r requirements.txt

WORKDIR /app_test
COPY ./tests/scripts/wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh

COPY /code/extractors /extractors
RUN pip3 install -e /extractors

COPY /code/transform /transform
RUN pip3 install -e /transform

COPY /code/load /load
RUN pip3 install -e /load