version: '3.8'
services:
  dev_with_gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - .:/app
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: Extraction_Results
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    command: ["tail", "-f", "/dev/null"]
    profiles: [gpu]
    dns:
      - 1.1.1.1
    # command: ["jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root"]
  
  dev_no_gpu:
    build:
      context: .
      dockerfile: Dockerfile.no_gpu
    volumes:
      - .:/app
    ports:
      - 8888:8888
    profiles: [no_gpu]
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: Extraction_Results
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    command: ["tail", "-f", "/dev/null"]
    dns:
      - 1.1.1.1

  anzograph:
    image: cambridgesemantics/anzograph:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /DB/anzograph-data:/opt/anzograph-data

  # virtuoso:
  #   image: openlink/virtuoso-opensource-7:latest
  #   ports:
  #     - "1111:1111"
  #     - "8890:8890"
  #   environment:
  #     DBA_PASSWORD: my_strong_password
  #   volumes:
  #     - /DB/virtuoso-data:/opt/virtuoso-opensource/database

  # mysql:
  #   image: mysql:latest
  #   hostname: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password123
  #     MYSQL_DATABASE: Extraction_Results
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password123
  #   ports:
  #     - "3306:3306"
  
  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   restart: always
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - mysql
  #   environment:
  #     # PMA_ARBITRARY: 1
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password123
  #     MYSQL_ROOT_PASSWORD: password123
      
