version: '3'
services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: Extraction_Results
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    command: ["tail", "-f", "/dev/null"]
    dns:
      - 1.1.1.1
    # command: ["jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root"]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: Extraction_Results
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      # PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password123
      
